# fly.toml app configuration file generated for komari-fdnprq on 2026-01-22T01:56:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'komari-fdnprq'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 25774
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[mounts]
source = "komari_data"
destination = "/app/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
